### ISSUE TITLE
API -> Buy Contract -> Contract purchased with duration as 100 days but shown as 100+ days on portfolio

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-extjs#57]
Contract has been created using API Console with following parameters for 100 days

http://rmg-prod.apigee.net/v1/binary/contract/CALL/frxUSDJPY/day/100/USD/50/0/0/0

But, it shows end time as 100 plus days as shown in attached screenshot
![100days](https://cloud.githubusercontent.com/assets/8477011/4701313/d876fca0-5857-11e4-929f-5b3f22455966.png)

**Comment by frank-binary** [comment]
For multi-day contracts, the end-date is rolled forward to end-of-trading time, so I don't believe there is any bug here.  Please re-raise if issue.
