### ISSUE TITLE
Account statement

### ISSUE THREAD

**Issue by AntonDriemin** [binary-com/binary-extjs#77]
Implement statement widget like this: https://www.binary.com/d/statement.cgi?l=EN

**Comment by AntonDriemin** [comment]
Frank, please let me know what do you think about following:

1. To implement account statement widget, I need to get description field in response of /account/statement request:

```javascript
{
      "balance_after": "9685.0700",
      "amount": "0.0000",
      "who": "AUTOSELL",
      "contract_id": "2732766048",
      "id": "5352442728",
      "transaction_time": 1420618260,
      "action_type": "sell",
      "description": "USD <strong>39.54</strong> payout if AUD/CAD is strictly <strong>higher</strong> than <strong>entry spot</strong> at 30 minutes after contract start time.",
    },
     {
      "balance_after": "9685.0700",
      "amount": "110.0000",
      "who": "AUTOSELL",
      "contract_id": "2732926648",
      "id": "5352442688",
      "transaction_time": 1420618260,
      "action_type": "sell",
      "description": "USD <strong>39.54</strong> payout if AUD/CAD is strictly <strong>higher</strong> than <strong>entry spot</strong> at 30 minutes after contract start time.",
    },
```
Can you please add description to the returning aray?

**Comment by frank-binary** [comment]
done, see issue 78

**Comment by AntonDriemin** [comment]
@frank-binary I see you added pagination, thank you. But I need to get total count to implement it.

**Comment by frank-binary** [comment]
actually, pagination was always there.. it probably did not say it at the
Console.  But yes I see.. you do need to know the total count.  Please do
raise another issue for that.
