### ISSUE TITLE
Portfolio performance improvement

### ISSUE THREAD

**Issue by AntonDriemin** [binary-com/binary-extjs#78]
Frank, in response of the /portfolio I'm getting array like this:

```javascript
"contracts":  [
     {
      "is_expired": 0,
      "contract_id": "2744788548",
      "expiry_daily": 0,
      "start_time": 1420725596,
      "expiry_time": 1420727396,
      "payout_price": "39.54",
      "underlying_symbol": "frxAUDCAD",
      "contract_type": "FLASHU",
      "purchase_time": 1420725596,
      "buy_price": "20",
      "settlement_time": 1420727396
    },
//.............
  ]
```

Bu only in response of /portfolio/{contract_id} I can get **description** field:
```javascript
 "contract":  {
    "is_expired": 0,
    "recomputed_price": 22.53,
    "contract_id": "2744788548",
    "expiry_daily": 0,
    "start_time": 1420725596,
    "description": "USD <strong>39.54</strong> payout if AUD/CAD is strictly <strong>higher</strong> than <strong>entry spot</strong> at 30 minutes after contract start time.",
    "expiry_time": 1420727396,
//.......
```

To display user's portfolio, I need to send request for every row to get description.
Do you have possibility to add **description** field in every array item, returning in response of /portfolio call?
This issue similar to /account/statement problem #77

**Comment by frank-binary** [comment]
Yes I see what you mean.
It is a performance issue.. perhaps, we should make it an optional query
parameter ?  " ?description=1 " or something like that ?
I am really hoping to return to webapi support this week.  Thanks for your
patience while i've been on other tasks.

**Comment by AntonDriemin** [comment]
@frank-binary I think its ok to use description=1 

(in future I will localize description and will generate it on UI level)

**Comment by frank-binary** [comment]
As of next release you can now say &description=1 on both /account/statement and /portfolio calls.
This will show the 'longcode' as requested.
(There's nearly always a new release each day).
