### ISSUE TITLE
Tick unit for /contract call

### ISSUE THREAD

**Issue by AntonDriemin** [binary-com/binary-extjs#95]
Previously I was called to 
http://rmg-prod.apigee.net/v1/binary/contract/FLASHD/frxUSDJPY/sec/?/USD/30/0/0/0
to get tick contract price, which is incorrect.

@frank-binary could you please add 'tick' duration unit to allow me to get tick-contract price?

**Comment by frank-binary** [comment]
Indeed, I see this fix as the same as this one :
https://github.com/binary-com/binary-extjs/issues/73

.. which is in progress.

**Comment by frank-binary** [comment]
Update:  issues/73 was a different issue after all. 
This issue (95) is valid and stays open.  In progress.

**Comment by AntonDriemin** [comment]
please let me know if I can start working on my part

**Comment by frank-binary** [comment]
Ok, please try 'tick' duration units now.   btw note that 'tick' duration units are supported for randoms and digits etc; I don't think the website allows them for things like USDJPY; does it?  Our offerings config info is possibly wrong here too.
